# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='val',
            name='exception',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='val',
            name='result',
            field=models.IntegerField(null=True),
        ),
    ]
